name: Build and Deploy Worker

on:
  push:
    tags:
      - "*"

jobs:
  worker:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node 16.15.1
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.1

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Publish
        run: npm run deploy
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
          CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
          TWT_CONSUMER_KEY: ${{ secrets.TWT_CONSUMER_KEY }}
          TWT_CLIENT_ID_0: ${{ secrets.TWT_CLIENT_ID_0 }}
          TWT_CLIENT_ID_1: ${{ secrets.TWT_CLIENT_ID_1 }}
          TWT_TOKEN: ${{ secrets.TWT_TOKEN }}
